config/routes.rb
Monospace::Application.routes.draw do
  resources :camps

  resources :projects

  root :to => "home#index"
  match 'register/:camp_id' => 'users#new', :as => :register
  match "sign_in" => "sessions#new", :as => :sign_in
  match "sign_out" => "sessions#destroy", :as => :sign_out
  match "edit_profile" => "users#edit", :as => :edit_profile

  resources :users
  resources :sessions

end

app/models/camp.rb
class Camp < ActiveRecord::Base
  
  has_many :users, :dependent=> :nullify
  has_many :billing_infos, :through => :users

end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  
  before_filter :admin_required
  
# GET /camps
  # GET /camps.xml
  def index
    @camps = Camp.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @camps }
    end
  end

  # GET /camps/1
  # GET /camps/1.xml
  def show
    @camp = Camp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @camp }
    end
  end

  # GET /camps/new
  # GET /camps/new.xml
  def new
    @camp = Camp.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @camp }
    end
  end

  # GET /camps/1/edit
  def edit
    @camp = Camp.find(params[:id])
  end

  # POST /camps
  # POST /camps.xml
  def create
    @camp = Camp.new
    @camp.save(:validate => false)
    begin
     response = Stripe::Plan.create( :amount => params[:camp][:cost].to_i * 100, :interval => 'month', :name => params[:camp][:name] , :currency => 'usd', :id => @camp.id )
     if @camp.update_attributes(params[:camp])
       redirect_to(@camp, :notice => 'Camp was successfully created.')
     else
       render :action => "edit"
     end
    rescue Exception => e
      @camp.destroy
      @camp = Camp.new(params[:camp])
      @camp.errors[:base] << "Exception #{e.class}: #{e.message}"
      render :action => "new"
    end
  end

  # PUT /camps/1
  # PUT /camps/1.xml
  def update
    @camp = Camp.find(params[:id])
    begin
     if @camp.valid?
      camp = Stripe::Plan.retrieve(@camp.id.to_s)
      camp.delete
      Stripe::Plan.create( :amount => params[:camp][:cost].to_i * 100, :interval => 'month', :name => params[:camp][:name] , :currency => 'usd', :id => @camp.id )
      if @camp.update_attributes(params[:camp])
        redirect_to(@camp, :notice => 'Camp was successfully updated.')
      else
        render :action => "edit"
      end
     end	
    rescue Exception => e
      @camp.errors[:base] << "Exception #{e.class}: #{e.message}"
      render :action => "edit"
    end
  end

  # DELETE /camps/1
  # DELETE /camps/1.xml
  def destroy
    @camp = Camp.find(params[:id])
    begin
      camp = Stripe::Plan.retrieve(@camp.id.to_s) 
      camp.delete
      if @camp.destroy
       redirect_to(camps_url, :notice => 'Camp was successfully destroyed.')
      else
       redirect_to(camps_url)
      end
    rescue Exception => e
      @camp.errors[:base] << "Exception #{e.class}: #{e.message}"
      redirect_to(camps_url)
    end
  end

end

app/helpers/camps_helper.rb
module CampsHelper
end

app/views/camps/_form.html.erb
<%= form_for(@camp) do |f| %>
  <% if @camp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camp.errors.count, "error") %> prohibited this camp from being saved:</h2>

      <ul>
      <% @camp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

        <div class="clearfix">
          <%= f.label :name %>
          <div class="input">
            <%= f.text_field :name %>
          </div>
        </div>

        <div class="clearfix">
          <%= f.label :cost %>
          <div class="input">
            <%= f.text_field :cost %>
          </div>
        </div>
  <div class="actions">
    <%= f.submit((defined?(editing) ? "Update" : "Submit"), :class => "btn primary") %>
  </div>
<% end %>

app/views/camps/edit.html.erb
<h1>Editing camp</h1>

<%= render 'form' %>

<%= link_to 'Show', @camp %> |
<%= link_to 'Back', camps_path %>

app/views/camps/index.html.erb
<h1>Listing camps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Cost</th>
    <th></th>
    <th></th>
  </tr>

<% @camps.each do |camp| %>
  <tr>
    <td><%= camp.name %></td>
    <td><%= camp.cost %></td>
    <td><%= link_to 'Edit', edit_camp_path(camp) %></td>
    <td><%= link_to 'Destroy', camp, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Camp', new_camp_path %>

app/views/camps/new.html.erb
<h1>New camp</h1>

<%= render 'form' %>

<%= link_to 'Back', camps_path %>

app/views/camps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @camp.name %>
</p>

<p>
  <b>Cost:</b>
  <%= @camp.cost %>
</p>


<%= link_to 'Edit', edit_camp_path(@camp) %> |
<%= link_to 'Back', camps_path %>