config/routes.rb
Monospace::Application.routes.draw do
  resources :camps

  resources :projects

  root :to => "home#index"
  match 'register/:camp_id' => 'users#new', :as => :register
  match "sign_in" => "sessions#new", :as => :sign_in
  match "sign_out" => "sessions#destroy", :as => :sign_out
  match "edit_profile" => "users#edit", :as => :edit_profile

  resources :users
  resources :sessions

end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>Monospace</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag "https://js.stripe.com/v1/" %>
    <%= javascript_tag "Stripe.publishableKey = '#{STRIPE_PUBLIC_KEY}';" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>

  </head>

  <body>
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <h3><%= link_to "Racevine Product", root_path %></h3>
          <ul class="nav">
            <% if current_user %>
               <li>
                <%= link_to "Sign Out", sign_out_path %>
              </li>
              <% if current_user.is_admin? %>
                <li>
                  <%= link_to "Create Camp", new_camp_path %>
                </li>
              <% end %>
            <% else %>
              <li>
                <%= link_to "Admin Login", sign_in_path %>
              </li>
              <li>
                <%= link_to "Camps", root_path %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="main container">
      <div class="row">
        <div class="span6 columns">
          <% if flash.notice %>
            <div class="alert-message block-message success" id="notice">
              <%= flash.notice %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>